version: '3'
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
      - /app/vendor
      - ${NAEMON_SOCKET_PATH}:${NAEMON_SOCKET_PATH}
    ports:
      - 8000:8000
    depends_on:
      - db

  queue:
    container_name: Queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      #MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD:-}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-} # Use this for setting the root password
      # Or use MYSQL_ALLOW_EMPTY_PASSWORD if you want to allow an empty root password
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db

networks:
  laravel-exa:
    driver: bridge

volumes:
  db:
    driver: local
